version: '3'

services:
    app:
        container_name: ZythologueAME-app
        build:
            context: ./docker/php/
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./app/:/var/www/
        networks:
            - ZythologueAME

    db:
        image: postgres:12.18
        build:
            context: ./docker/DB/
            dockerfile: dockerfile
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: zythologie_db
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - ZythologueAME
        depends_on:
            - app

volumes:
    db-data:


networks:
    ZythologueAME:
