insert into brewery (brewery_name, brewery_country) values ('Hilll, Raynor and Homenick', 'Comoros');
insert into brewery (brewery_name, brewery_country) values ('Jones Group', 'Russia');
insert into brewery (brewery_name, brewery_country) values ('Gerhold-Kris', 'China');
insert into brewery (brewery_name, brewery_country) values ('Hills-Rodriguez', 'Thailand');
insert into brewery (brewery_name, brewery_country) values ('O''Hara Group', 'Syria');
insert into brewery (brewery_name, brewery_country) values ('O''Connell Inc', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Stamm, Huels and Pouros', 'Portugal');
insert into brewery (brewery_name, brewery_country) values ('Gibson, Krajcik and McLaughlin', 'Netherlands');
insert into brewery (brewery_name, brewery_country) values ('Waelchi, Wolf and Schowalter', 'China');
insert into brewery (brewery_name, brewery_country) values ('Padberg Inc', 'China');
insert into brewery (brewery_name, brewery_country) values ('Fisher Inc', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Mosciski, Treutel and Mayer', 'Russia');
insert into brewery (brewery_name, brewery_country) values ('White-Lockman', 'Czech Republic');
insert into brewery (brewery_name, brewery_country) values ('Marquardt and Sons', 'Tanzania');
insert into brewery (brewery_name, brewery_country) values ('Cartwright-Wilkinson', 'Portugal');
insert into brewery (brewery_name, brewery_country) values ('Mayert-Roberts', 'Portugal');
insert into brewery (brewery_name, brewery_country) values ('Rohan-Streich', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Gusikowski-McCullough', 'Poland');
insert into brewery (brewery_name, brewery_country) values ('Kiehn-Nolan', 'China');
insert into brewery (brewery_name, brewery_country) values ('Carter-Rosenbaum', 'Thailand');
insert into brewery (brewery_name, brewery_country) values ('Wintheiser, Kilback and Shanahan', 'United States');
insert into brewery (brewery_name, brewery_country) values ('Gislason Inc', 'Dominican Republic');
insert into brewery (brewery_name, brewery_country) values ('Hickle, Gibson and Towne', 'Portugal');
insert into brewery (brewery_name, brewery_country) values ('McLaughlin-Lockman', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Senger-Watsica', 'Vietnam');
insert into brewery (brewery_name, brewery_country) values ('West, Johns and Cummings', 'China');
insert into brewery (brewery_name, brewery_country) values ('Weber and Sons', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Ankunding and Sons', 'Ukraine');
insert into brewery (brewery_name, brewery_country) values ('Bauch, Koelpin and Hessel', 'Brazil');
insert into brewery (brewery_name, brewery_country) values ('Beier Group', 'China');
insert into brewery (brewery_name, brewery_country) values ('Kautzer, Bins and Leannon', 'Sweden');
insert into brewery (brewery_name, brewery_country) values ('Okuneva, Jenkins and Auer', 'Brazil');
insert into brewery (brewery_name, brewery_country) values ('Turcotte-Torp', 'Japan');
insert into brewery (brewery_name, brewery_country) values ('Purdy-Goodwin', 'Thailand');
insert into brewery (brewery_name, brewery_country) values ('Bernier-Flatley', 'Japan');
insert into brewery (brewery_name, brewery_country) values ('Orn and Sons', 'Ukraine');
insert into brewery (brewery_name, brewery_country) values ('Donnelly-MacGyver', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Littel-Kshlerin', 'France');
insert into brewery (brewery_name, brewery_country) values ('Romaguera-McDermott', 'China');
insert into brewery (brewery_name, brewery_country) values ('White-Friesen', 'Honduras');
insert into brewery (brewery_name, brewery_country) values ('Bauch-Flatley', 'Portugal');
insert into brewery (brewery_name, brewery_country) values ('Jakubowski, Collins and Willms', 'Iran');
insert into brewery (brewery_name, brewery_country) values ('Bartell Group', 'Russia');
insert into brewery (brewery_name, brewery_country) values ('Fay Group', 'China');
insert into brewery (brewery_name, brewery_country) values ('Schmidt and Sons', 'Mongolia');
insert into brewery (brewery_name, brewery_country) values ('Jones and Sons', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Altenwerth-Stanton', 'China');
insert into brewery (brewery_name, brewery_country) values ('Pagac-Lind', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Crooks, Wilderman and Mosciski', 'Poland');
insert into brewery (brewery_name, brewery_country) values ('Monahan, Kihn and Ledner', 'United States');
insert into brewery (brewery_name, brewery_country) values ('Hickle LLC', 'Russia');
insert into brewery (brewery_name, brewery_country) values ('Gerlach-Christiansen', 'China');
insert into brewery (brewery_name, brewery_country) values ('Prosacco-Rempel', 'China');
insert into brewery (brewery_name, brewery_country) values ('Hilpert and Sons', 'South Africa');
insert into brewery (brewery_name, brewery_country) values ('Jenkins, Wilkinson and Kertzmann', 'Philippines');
insert into brewery (brewery_name, brewery_country) values ('Tillman-Mayert', 'China');
insert into brewery (brewery_name, brewery_country) values ('Goldner, Mills and Little', 'Bulgaria');
insert into brewery (brewery_name, brewery_country) values ('Mertz, Gottlieb and Hilll', 'Morocco');
insert into brewery (brewery_name, brewery_country) values ('Littel Group', 'China');
insert into brewery (brewery_name, brewery_country) values ('Runolfsdottir-Pfannerstill', 'China');
insert into brewery (brewery_name, brewery_country) values ('Terry-Waelchi', 'Peru');
insert into brewery (brewery_name, brewery_country) values ('Grant-Wiza', 'China');
insert into brewery (brewery_name, brewery_country) values ('Funk, Sanford and Hackett', 'Germany');
insert into brewery (brewery_name, brewery_country) values ('Yost Inc', 'Nigeria');
insert into brewery (brewery_name, brewery_country) values ('Lind-Goodwin', 'Brazil');
insert into brewery (brewery_name, brewery_country) values ('Heidenreich Inc', 'Argentina');
insert into brewery (brewery_name, brewery_country) values ('Cassin, Balistreri and Kilback', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Hirthe-Considine', 'Finland');
insert into brewery (brewery_name, brewery_country) values ('Beatty Inc', 'Georgia');
insert into brewery (brewery_name, brewery_country) values ('Hudson Group', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Paucek and Sons', 'Sudan');
insert into brewery (brewery_name, brewery_country) values ('O''Keefe, Schneider and Goyette', 'Thailand');
insert into brewery (brewery_name, brewery_country) values ('Turcotte-Orn', 'Japan');
insert into brewery (brewery_name, brewery_country) values ('Cummings-Osinski', 'Brazil');
insert into brewery (brewery_name, brewery_country) values ('Bernier-Altenwerth', 'United States');
insert into brewery (brewery_name, brewery_country) values ('Schumm-Satterfield', 'Nepal');
insert into brewery (brewery_name, brewery_country) values ('Hilll-Feil', 'Philippines');
insert into brewery (brewery_name, brewery_country) values ('Hegmann-Moen', 'Tanzania');
insert into brewery (brewery_name, brewery_country) values ('Considine-Walker', 'Philippines');
insert into brewery (brewery_name, brewery_country) values ('Ebert Group', 'Poland');
insert into brewery (brewery_name, brewery_country) values ('Ortiz, Ebert and Haag', 'Ukraine');
insert into brewery (brewery_name, brewery_country) values ('Kohler-Nicolas', 'Panama');
insert into brewery (brewery_name, brewery_country) values ('Bednar and Sons', 'Indonesia');
insert into brewery (brewery_name, brewery_country) values ('Brakus-Ferry', 'Russia');
insert into brewery (brewery_name, brewery_country) values ('Schinner Group', 'Brazil');
insert into brewery (brewery_name, brewery_country) values ('Weissnat and Sons', 'China');
insert into brewery (brewery_name, brewery_country) values ('Prohaska Inc', 'Argentina');
insert into brewery (brewery_name, brewery_country) values ('Romaguera Inc', 'Nigeria');
insert into brewery (brewery_name, brewery_country) values ('Mayer LLC', 'Lithuania');
insert into brewery (brewery_name, brewery_country) values ('Frami-Leuschke', 'Norway');
insert into brewery (brewery_name, brewery_country) values ('Smith Inc', 'China');
insert into brewery (brewery_name, brewery_country) values ('Treutel-Thompson', 'Colombia');
insert into brewery (brewery_name, brewery_country) values ('Windler, Senger and Borer', 'Egypt');
insert into brewery (brewery_name, brewery_country) values ('Hermiston-Kautzer', 'Kazakhstan');
insert into brewery (brewery_name, brewery_country) values ('Johnson LLC', 'Peru');
insert into brewery (brewery_name, brewery_country) values ('Jacobs, Raynor and Kuhn', 'Russia');
insert into brewery (brewery_name, brewery_country) values ('Schiller, Conn and Batz', 'Philippines');
insert into brewery (brewery_name, brewery_country) values ('Halvorson-Wilkinson', 'Sri Lanka');
insert into brewery (brewery_name, brewery_country) values ('O''Connell and Sons', 'United States');
insert into brewery (brewery_name, brewery_country) values ('Bechtelar Inc', 'Philippines');
