insert into category (category_name) values ('IPA');
insert into category (category_name) values ('Stout');
insert into category (category_name) values ('Pilsner');
insert into category (category_name) values ('Saison');
insert into category (category_name) values ('Porter');
insert into category (category_name) values ('Wheat');
insert into category (category_name) values ('Lager');
insert into category (category_name) values ('Pale Ale');
insert into category (category_name) values ('Amber Ale');
insert into category (category_name) values ('Hefeweizen');
insert into category (category_name) values ('Belgian Tripel');
insert into category (category_name) values ('Brown Ale');
insert into category (category_name) values ('Barleywine');
insert into category (category_name) values ('Gose');
insert into category (category_name) values ('Kölsch');
insert into category (category_name) values ('Scotch Ale');
insert into category (category_name) values ('Doppelbock');
insert into category (category_name) values ('Berliner Weisse');
insert into category (category_name) values ('Cream Ale');
insert into category (category_name) values ('Rauchbier');
